{% set name = "pytest-mypy" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5a667d9a2b66bf98b3a494411f221923a6e2c3eafbe771104951aaec8985673d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4
    - setuptools_scm
  run:
    - mypy >=0.500
    - pytest >=2.8
    - filelock
    - python >=3.4

test:
  imports:
    - pytest_mypy

about:
  home: https://github.com/dbader/pytest-mypy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Mypy static type checker plugin for Pytest
  doc_url: https://pypi.org/project/pytest-mypy/
  dev_url: https://github.com/dbader/pytest-mypy

extra:
  recipe-maintainers:
    - sduc
